import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Todo List',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  var userToken: Boolean = false;

  return (
    <html lang="en" data-theme="oldal">
      <body className={inter.className}>
        <nav>
          <div className="navbar bg-base-100">
            <div className="flex-1">
              <Link href={"/"} className="btn btn-ghost normal-case text-xl">Todo List</Link>
            </div>
            <div className="flex-none gap-2">
              <div className="form-control">
                <input type="text" placeholder="Search" className="input input-bordered w-24 md:w-auto" />
              </div>
              {
                !userToken ?
                  <div className="dropdown dropdown-end">

                    <Link href={"/signup"} className='btn' >Sign Up</Link>
                    <Link href={"/signin"} className='btn bg-ecru-600 text-cornell_red-300' >Sign In</Link>

                  </div>
                  :
                  <div className="dropdown dropdown-end">

                    <label tabIndex={0} className="btn btn-ghost btn-circle avatar">
                      <div className="w-10 rounded-full">
                        <img src="/images/stock/photo-1534528741775-53994a69daeb.jpg" />
                      </div>
                    </label>

                    <ul tabIndex={0} className="mt-3 z-[1] p-2 shadow menu menu-sm dropdown-content bg-base-100 rounded-box w-52">
                      <li>
                        <a className="justify-between">
                          Profile
                          <span className="badge">New</span>
                        </a>
                      </li>
                      <li><a>Settings</a></li>
                      <li><a>Logout</a></li>
                    </ul>

                  </div>
              }
            </div>
          </div>
        </nav>
        <main className='min-h-screen container mx-auto'>
          {children}
        </main>
      </body>
    </html>
  )
}
